apiVersion: v1
kind: Pod
metadata:
  labels:
    version: v1
    zone: prod
  name: hello-pod
spec:
  containers:
    - image: nigelpoulton/k8sbook:1.0
      name: hello-ctr
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "128Mi"
          cpu: "0.5"
